### ISSUE TITLE
where_values with where_template : what is the values expected ?

### ISSUE THREAD

**Issue by yougis** [intake/intake-sql#11]
I am trying to work with SQLSourceManualPartition 
and I can't figure out what values is expected in where_value

I have this template : 
```
SQLSourceManualPartition(uri='postgresql://admsig@pgsql2-prod.province-sud.prod:5432/ddr', sql_expr='select * from schema.table', where_values=[[0 ,100,200],[100,200,500]], where_template='WHERE id >= {} AND id < {} OR id = {}')
```
but I get a **tuple index out of range** error

It could be resolved if  we get all values unpacked at once
line 315
`where = [where_tmp.format(*values) for values in where]`

**Comment by martindurant** [comment]
Would you mind first trying with tuples rather than lists?
Otherwise, what you are saying makes a lot of sense, and I would encourage you to produce a PR with a change like this, and include your specific case as a test case (working on a local sqlite3 file, like the other tests).

**Comment by astrojuanlu** [comment]
I think I am observing this error, see for example:

```python
from intake_sql.intake_sql import read_sql_query

where = [(1, 2), (3, 4)]
read_sql_query('sqlite://', "SELECT * FROM table", where, 'WHERE index >= {} AND index < {}')
```

this raises:

```
IndexError: Replacement index 1 out of range for positional args tuple
```

because `'WHERE index >= {} AND index < {}'.format((1, 2))` gives an error. However, as @yougis suggested, changing

https://github.com/intake/intake-sql/blob/5446e44d5130a7cfbf1189f610780aadad0db316/intake_sql/intake_sql.py#L311

for `where = [where_tmp.format(*values) for values in where]` would fix the error.
